"""Item persistence: YAML files are the source of truth; SQLite is a rebuildable
index. All writes go through here so the two never drift (the DB is regenerated
from files by `reindex`, never hand-edited)."""
from __future__ import annotations

import json
import sqlite3
from pathlib import Path

import yaml

from . import paths


def item_path(item: dict) -> Path:
    """store/items/<category>/<id>.yaml — sharded by category to keep dirs browsable."""
    category = item.get("category", "uncategorized")
    return paths.ITEMS_DIR / category / f"{item['id']}.yaml"


def save_item(item: dict) -> Path:
    path = item_path(item)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        yaml.safe_dump(item, fh, sort_keys=False, allow_unicode=True)
    return path


def load_item(path) -> dict:
    with open(path) as fh:
        return yaml.safe_load(fh)


# --- orders ---------------------------------------------------------------

def order_path(order_id: str) -> Path:
    return paths.ORDERS_DIR / f"{order_id}.yaml"


def save_order(order: dict) -> Path:
    path = order_path(order["id"])
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as fh:
        yaml.safe_dump(order, fh, sort_keys=False, allow_unicode=True)
    return path


def find_item_by_part(mpn: str | None, digikey_pn: str | None) -> tuple[Path, dict] | None:
    """Dedup lookup: match on MPN (case-insensitive) or a known DigiKey part no."""
    mpn_l = (mpn or "").lower()
    for path, item in iter_items():
        if mpn_l and (item.get("mpn") or "").lower() == mpn_l:
            return path, item
        if digikey_pn and (item.get("vendor_pns") or {}).get("digikey") == digikey_pn:
            return path, item
    return None


def iter_items():
    if not paths.ITEMS_DIR.exists():
        return
    for path in sorted(paths.ITEMS_DIR.rglob("*.yaml")):
        yield path, load_item(path)


def get_item(item_id: str) -> tuple[Path, dict] | None:
    for path, item in iter_items():
        if item.get("id") == item_id:
            return path, item
    return None


def find(query: str) -> list[dict]:
    q = query.lower()
    hits = []
    for _, item in iter_items():
        haystack = " ".join(
            str(item.get(f, "")) for f in ("id", "mpn", "manufacturer", "description", "category")
        ).lower()
        if q in haystack:
            hits.append(item)
    return hits


# --- SQLite index (rebuildable) -------------------------------------------

def reindex() -> int:
    """Rebuild inventory.db from the YAML files. Returns the item count."""
    if paths.INDEX_DB.exists():
        paths.INDEX_DB.unlink()
    con = sqlite3.connect(paths.INDEX_DB)
    con.execute(
        """CREATE TABLE items (
               id TEXT PRIMARY KEY, type TEXT, category TEXT,
               manufacturer TEXT, mpn TEXT, qty REAL, description TEXT,
               params_json TEXT, file TEXT
           )"""
    )
    n = 0
    for path, item in iter_items():
        con.execute(
            "INSERT OR REPLACE INTO items VALUES (?,?,?,?,?,?,?,?,?)",
            (
                item.get("id"), item.get("type"), item.get("category"),
                item.get("manufacturer"), item.get("mpn"), item.get("qty"),
                item.get("description"), json.dumps(item.get("params") or {}),
                str(path.relative_to(paths.ROOT)),
            ),
        )
        n += 1
    con.commit()
    con.close()
    return n


def export_markdown() -> Path:
    """Generate a flat human/agent-readable table at views/parts.md."""
    paths.VIEWS_DIR.mkdir(parents=True, exist_ok=True)
    out = paths.VIEWS_DIR / "parts.md"
    rows = [item for _, item in iter_items()]
    rows.sort(key=lambda i: (i.get("category", ""), i.get("id", "")))
    lines = [
        "# Inventory — parts index",
        "",
        "_Generated by `inv export md`. Do not edit by hand._",
        "",
        "| ID | Type | Category | Mfr | MPN | Qty | Description |",
        "|----|------|----------|-----|-----|-----|-------------|",
    ]
    for i in rows:
        lines.append(
            f"| {i.get('id','')} | {i.get('type','')} | {i.get('category','')} "
            f"| {i.get('manufacturer','')} | {i.get('mpn','')} | {i.get('qty','')} "
            f"| {i.get('description','')} |"
        )
    out.write_text("\n".join(lines) + "\n")
    return out
