"""add embeddings support

Revision ID: 2d34c8159fd3
Revises: 
Create Date: 2026-01-18 01:30:12.482803

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '2d34c8159fd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('heading_path', sa.String(length=500), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'chunk_index', name='unique_page_chunk')
    )
    with op.batch_alter_table('page_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_embeddings_page_id'), ['page_id'], unique=False)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embeddings_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('embeddings_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('embeddings_updated_at')
        batch_op.drop_column('embeddings_status')

    with op.batch_alter_table('page_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_embeddings_page_id'))

    op.drop_table('page_embeddings')
    # ### end Alembic commands ###
