"""Add Tag model and page_tags association table for bulk import

Revision ID: 7a20e2d1e99d
Revises: 141443313e0d
Create Date: 2026-01-18 23:44:50.646560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a20e2d1e99d'
down_revision = '141443313e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        # Add auto_generated as nullable first, set defaults, then make it non-nullable
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('model_name', sa.String(length=100), nullable=True))
        # Add verified as nullable first, set defaults, then make it non-nullable
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['verified_by_id'], ['id'])

    # Set default values for existing rows
    op.execute("UPDATE tags SET source = 'human' WHERE source IS NULL")
    op.execute("UPDATE tags SET auto_generated = false WHERE auto_generated IS NULL")
    op.execute("UPDATE tags SET verified = false WHERE verified IS NULL")
    
    # Now make the boolean columns non-nullable
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('auto_generated', nullable=False)
        batch_op.alter_column('verified', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by_id')
        batch_op.drop_column('verified')
        batch_op.drop_column('model_name')
        batch_op.drop_column('confidence')
        batch_op.drop_column('auto_generated')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
